name: Stock model
description: This AMP demonstrates how PEFT and other fine-tuning optimization techniques can be used for efficient and effective customization of an existing LLM to perform new tasks.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2023-07-22"


runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard
    addons: ["Spark 3.2.3 - CDE 1.19.2 - HOTFIX-2"]
    
tasks:
  - type: run_session
    name: LoadData
    script: amp_retail_0/dataRead.py
    short_summary: loaddata 
    long_summary: load data from csv.
    cpu: 2
    memory: 4

  - type: run_session
    name: adjustDates
    script: amp_retail_0/adjustDate.py
    short_summary: adjustdate
    cpu: 2
    memory: 4
  
  - type: run_session
    name: TrainModel
    script: amp_retail_stock/train_model_stock.py
    short_summary: train model and create experiments
    long_summary: train model and create experiments
    cpu: 2
    memory: 4
 
   - type: run_session
    name: GetChampion
    script: amp_retail_stock/get_champion_viz_stock.py
    short_summary: deploy best model
    long_summary: deploy best model
    cpu: 2
    memory: 4



  - type: create_job
    name: Job for check the model
    short_summary: Create Job to check the model
    entity_label: checkmodel
    script: amp_retail_stock/check_model_stock.py
    arguments: None
    long_summary: check model in case it is necessary to retrain it
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: create_job
    name: Job to send email with metrics (adjust the email)
    short_summary: ob to send email with metrics (adjust the email)
    entity_label: fine_tune_sql
    script: amp_retail_stock/avisoPerformance.py
    arguments: None
    long_summary: ob to send email with metrics (adjust the email)
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: create_job
    name: Job for retrain
    short_summary: Create Job for fine-tuning on Detox Dataset
    entity_label: fine_tune_detox
    script: amp_retail_stock/train_model_stock.py
    arguments: None
    long_summary: Create job to fine-tune an LLM on the s-nlp/paradetox dataset. This job will not be automatically launched during AMP startup. A sample LoRA adapter fine-tuned with this job script and dataset is included in the git repository.
    cpu: 2
    memory: 8
    environment:
      TASK_TYPE: CREATE/RUN_JOB
      
      
  - type: create_job
    name: Job to deploy best model
    short_summary: Job to deploy best model
    entity_label: fine_tune_detox
    script: amp_retail_stock/get_champion_viz_stock.py
    arguments: None
    long_summary: Job to deploy best model
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB
  
